server:
  port: 4004

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service-route
              uri: http://host.docker.internal:4005
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1


            - id: patient-service-route
              uri: http://host.docker.internal:4000
              predicates:
                - Path=/api/patients/**
              filters:
                - StripPrefix=1
                - JwtValidation

            #api documentation
            - id: api-docs-auth-route
              uri: http://host.docker.internal:4005
              predicates:
                - Path=/api-docs/**
              filters:
                - RewritePath=/api-docs/auth,/v3/api-docs

            - id: api-docs-patient-route
              uri: http://host.docker.internal:4000
              predicates:
                - Path=/api-docs/**
              filters:
                - RewritePath=/api-docs/patients,/v3/api-docs
#              /v3/api-docs
#              /swagger-ui/index.html



